### ISSUE TITLE
No module named compat

### ISSUE THREAD

**Issue by roman-parkhunovskyi** [vovanec/supervisor_checks#1]
compat.py is not included into the latest version of supervisor installed via pip causing checks to fail:

```
Traceback (most recent call last):
  File "/home/user/work/tst/bin/supervisor_http_check", line 7, in <module>
    from supervisor_checks.bin.http_check import main
  File "/home/user/work/tst/lib/python2.7/site-packages/supervisor_checks/bin/http_check.py", line 14, in <module>
    from supervisor_checks.check_modules import http
  File "/home/user/work/tst/lib/python2.7/site-packages/supervisor_checks/check_modules/http.py", line 4, in <module>
    from supervisor.compat import httplib
ImportError: No module named compat
```

Is it possible to not use this file so far for compatibility with current supervisor versions?

**Comment by vovanec** [comment]
The problem is this library has never been really tested with supervisor 3 branch(python 2.7 only) as it was developed for supervisor 4 branch. I've fixed missing dependency module with recent commit. Please try supervisor_checks 0.4.1 and let me know whether it worked for you.

thanks
--Vovan
