### ISSUE TITLE
KeyError: 'SUPERVISOR_SERVER_URL'

### ISSUE THREAD

**Issue by lrkwz** [vovanec/supervisor_checks#15]
I think the error is not quite esplicative ... can you help me understand what is happening here?

```bash
$ supervisor_memory_check -N garanteasy-mail-import -n test -m 102400
Traceback (most recent call last):
  File "/home/lrkwz/.local/bin/supervisor_memory_check", line 11, in <module>
    sys.exit(main())
  File "/home/lrkwz/.local/lib/python3.6/site-packages/supervisor_checks/bin/memory_check.py", line 55, in main
    args.check_name, args.process_group, args.process_name, checks_config).run()
  File "/home/lrkwz/.local/lib/python3.6/site-packages/supervisor_checks/check_runner.py", line 62, in __init__
    self._rpc_client = childutils.getRPCInterface(self._environment)
  File "/home/lrkwz/.local/lib/python3.6/site-packages/supervisor/childutils.py", line 21, in getRPCInterface
    return xmlrpclib.ServerProxy('http://127.0.0.1', getRPCTransport(env))
  File "/home/lrkwz/.local/lib/python3.6/site-packages/supervisor/childutils.py", line 15, in getRPCTransport
    return SupervisorTransport(u, p, env['SUPERVISOR_SERVER_URL'])
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'SUPERVISOR_SERVER_URL'
```

BTW supervisord is running on python2.x (default on ubuntu 18.04)

**Comment by vovanec** [comment]
Hi @lrkwz , this script is not supposed to be run manually. Please refer to https://github.com/vovanec/supervisor_checks/issues/7 for more info. I am marking issue as duplicate. 

Please feel free to submit a pull request to enhance the error message.
