### ISSUE TITLE
run supervisor_tcp_check failure

### ISSUE THREAD

**Issue by zhoujw8792** [vovanec/supervisor_checks#7]
[root@NESP-WEB ~]# /opt/deps/env/bin/supervisor_tcp_check -g hdfs-over-ftp -n hdfs-over-ftp -t 30 -r 3 -p 2222
Traceback (most recent call last):
  File "/opt/deps/env/bin/supervisor_tcp_check", line 11, in <module>
    load_entry_point('supervisor-checks==0.7.0', 'console_scripts', 'supervisor_tcp_check')()
  File "build/bdist.linux-x86_64/egg/supervisor_checks/bin/tcp_check.py", line 59, in main
  File "build/bdist.linux-x86_64/egg/supervisor_checks/check_runner.py", line 60, in __init__
  File "/opt/deps/env/lib/python2.7/site-packages/supervisor/childutils.py", line 17, in getRPCInterface
    return xmlrpclib.ServerProxy('http://127.0.0.1', getRPCTransport(env))
  File "/opt/deps/env/lib/python2.7/site-packages/supervisor/childutils.py", line 11, in getRPCTransport
    return SupervisorTransport(u, p, env['SUPERVISOR_SERVER_URL'])
  File "/opt/deps/env/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'SUPERVISOR_SERVER_URL'

**Comment by vovanec** [comment]
These scripts are supervisor event listeners, not standalone tools. You can run them with -h/--help option but I think this is the only way you can run them as standalone CLI programs.

Please configure and run check as it described in documentation and let me know if you have any issue.

**Comment by tarasvaskiv** [comment]
Having similar issue here:
``Traceback (most recent call last):
  File "/usr/local/bin/supervisor_http_check", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/supervisor_checks/bin/http_check.py", line 87, in main
    args.check_name, args.process_group, args.process_name, checks_config).run()
  File "/usr/local/lib/python2.7/dist-packages/supervisor_checks/check_runner.py", line 62, in __init__
    self._rpc_client = childutils.getRPCInterface(self._environment)
  File "/usr/local/lib/python2.7/dist-packages/supervisor/childutils.py", line 17, in getRPCInterface
    return xmlrpclib.ServerProxy('http://127.0.0.1', getRPCTransport(env))
  File "/usr/local/lib/python2.7/dist-packages/supervisor/childutils.py", line 11, in getRPCTransport
    return SupervisorTransport(u, p, env['SUPERVISOR_SERVER_URL'])
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SUPERVISOR_SERVER_URL'

While running 2 processes under supervisor in docker container. Here is my supervisor.conf file
`[supervisord]
logfile=/var/log/yogasoft_supervisor.log
logfile_maxbytes=20MB
logfile_backups=5

[supevisorctl]
serverurl = unix:///tmp/supervisor.sock

[program:daphne]
command=bash -c "daphne -b 0.0.0.0 -p 8002 yogasoft.asgi:channel_layer"
[program:worker]
command=bash -c "managepy runserver 0.0.0.0:8000"`

**Comment by vovanec** [comment]
Hi @tarasvaskiv , 

These tools are supposed to be run by supervisor itself as a part of supervisor eventlistener framework. In your config file, I don't see any eventlistener module configuration. I'd expect to see something like:

```
[eventlistener: daphne_check]
environment = specify any environment variables here"
command=/usr/local/bin/supervisor_memory_check -g daphne -n daphne_check -c -m 2097152
stderr_logfile = /var/log/supervisor/daphne-stderr.log
stdout_logfile = /var/log/supervisor/daphne-stdout.log
events=TICK_60
```
